name: CI

on:
  push:
    branches:
      - '**'

# run the tests
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Change to project directory
        run: cd node/express-prisma-typescript

      - name: Install dependencies
        working-directory: node/express-prisma-typescript
        run: yarn install

      - name: Run tests
        working-directory: node/express-prisma-typescript
        run: yarn test
