name: CI

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Change to project directory
        run: cd node/express-prisma-typescript

      - name: Install dependencies
        run: |
          cd node/express-prisma-typescript
          yarn install

      - name: Run tests
        run: |
          cd node/express-prisma-typescript
          yarn test
